name: Build and Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the version of Node.js you need

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Modify this command according to your project

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Add your EC2 instance host here
          username: ${{ secrets.SSH_USERNAME }} # Add your SSH username here
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add your SSH private key here
          source: "." # Specify the source directory you want to deploy
          target: "/home/project" # Specify the target directory on the remote machine
